corpus:
  dev_override_path: data/dyck_mk/dyck_6_2/eos/dev.formal.txt 
  root: data/dyck_mk
  test_override_path: data/dyck_mk/dyck_6_2/eos/test.formal.txt 
  train_override_path: data/dyck_mk/dyck_6_2/eos/train.formal.txt 
language:
  bracket_types: 2
  dev_max_length: 228
  dev_max_stack_depth: 6
  dev_min_length: 184
  dev_sample_count: 400
  test_max_length: 2280
  test_max_stack_depth: 6
  test_min_length: 1840
  test_sample_count: 10000
  train_max_length: 228
  train_max_stack_depth: 6
  train_min_length: 184
  train_sample_count: 1000000
  length_effects: True
training:
  seed: 2
