data:
  dataset_name: dyck42
  dataset_type: dyckmk
  dev_path: data/dyck_mk/dyck_4_2/no_eos/dev.formal.txt
  test_path: data/dyck_mk/dyck_4_2/eos/test.formal.txt
  train_path: data/dyck_mk/dyck_4_2/no_eos/train.formal.txt
  vocab_path: data/dyck_mk/dyck_4_2/vocab.json
lm:
  batch_size: 16
  cell_type: standard
  dropout: 0.0
  embed_dim: 20
  hidden_dim: 20
  lm_path: models/dyck42-no_eos
  lm_type: rnnlm
  lr: 0.01
  num_layers: 1
  seed: 504
  use_eos: false
reporter:
  methods:
    close_bracket: null
    perplexity: null
  results_path: results/dyck42-no_eos
