data:
  dataset_name: dyck42
  dataset_type: dyckkm_ending
  dev_path: data/dyck_mk/dyck_4_2/eos/dev.formal.txt
  test_path: data/dyck_mk/dyck_4_2/eos/test.formal.txt
  train_path: data/dyck_mk/dyck_4_2/eos/train.formal.txt
  vocab_path: data/dyck_mk/dyck_4_2/vocab.json
lm:
  batch_size: 16
  cell_type: standard
  dropout: 0.0
  embed_dim: 20
  hidden_dim: 20
  lm_path: models/dyck42-eos
  lm_type: rnnlm
  lr: 0.01
  num_layers: 1
  seed: 501
  use_eos: true
reporter:
  methods:
  - dyck_ending
  results_path: results/dyck42-eos
truncation:
  lr: 0.01
  model_path: models/truncation/dyck42-eos
  model_type: dyckkm_ending
