data:
  dataset_name: scanls22
  dataset_type: scan
  dev_path: data/scan/length_split/dev.txt
  input_vocab_path: data/scan/scan_input_vocab.json
  target_vocab_path: data/scan/scan_target_vocab.json
  test_path: data/scan/length_split/tasks_test_length.txt
  train_path: data/scan/length_split/small_train.txt
lm:
  batch_size: 16
  decoder_cell_type: standard
  decoder_num_layers: 1
  dropout: 0.5
  embed_dim: 200
  encoder_cell_type: standard
  encoder_num_layers: 2
  hidden_dim: 200
  lm_path: models/ls-22_eos-False
  lm_type: seq2seq
  lr: 0.001
  seed: 500
  teacher_forcing_ratio: 0.5
  use_eos: false
reporter:
  methods:
    save_cache: null
  results_path: results/ls-22_eos-False
truncation:
  model_path: models/
  model_type: oracle
  truncation_path: models/ls-22_eos-False
