data:
  dataset_name: dyck82
  dataset_type: dyckmk
  dev_path: data/dyck_mk/dyck_8_2/eos/dev.formal.txt
  test_path: data/dyck_mk/dyck_8_2/eos/test.formal.txt
  train_path: data/dyck_mk/dyck_8_2/eos/train.formal.txt
  vocab_path: data/dyck_mk/dyck_8_2/vocab.json
lm:
  batch_size: 64
  cell_type: standard
  dropout: 0.0
  embed_dim: 40
  hidden_dim: 40
  lm_path: models/dyck82-eos
  lm_type: rnnlm
  lr: 0.01
  num_layers: 1
  seed: 502
  use_eos: true
reporter:
  methods:
    close_bracket: null
    perplexity: null
  results_path: results/dyck82-eos
